PLATFORM = 'Android'
DEVICE_NAME = 'MI_5X'
APP_PAKEAGE = 'com.jingdong.app.mall'
APP_ACTIVITY = '.MainFrameActivity'

DRIVER_SERVER='http://127.0.0.1:4723/wd/hub'
TIMEOUT = 300

#滑动点
FLICK_START_X = 300
FLICK_START_Y = 300
FLICK_DISTANCE = 700

KEYWORD = 'Ipad'
SCROLL_SLEEP_TIME = 3